{% set version = "1.11.5" %}

package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-{{ version }}.tar.gz
    url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
    sha256: 49f99971182864abed9ac42de10545a92392d88f7dbcfdb11afe449a7eb754fe
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
        - disable_jpeg12.patch  # [win]
        - windowshdf5.patch  # [win]
        - install_scripts.patch
        - MSC_VER_1900_snprintf.patch  # [win]

build:
    number: 3
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python
        - setuptools
        - cmake  # [win]
        - numpy x.x
        - hdf4  # [not win]
        - hdf5 1.8.17|1.8.17.*
        - geos 3.5.*
        - proj.4 4.9.3
        - xerces-c
        - libnetcdf 4.4.*
        - libdap4 3.18.*  # [not win]
        - libtiff 4.0.*
        - libpng >=1.6.23,<1.7
        - zlib 1.2.*  # [not win]
        - jpeg 9*
        - postgresql  # [not win]
        - giflib 5.1.*  # [not win]
        - json-c  # [not win]
        - freexl
        - openjpeg
        - curl
        - expat
        - sqlite 3.13.*  # [not win]
        - libspatialite  # [not win]
    run:
        - python
        - numpy x.x
        - hdf4  # [not win]
        - hdf5 1.8.17|1.8.17.*
        - geos 3.5.*
        - proj.4 4.9.3
        - xerces-c
        - libnetcdf 4.4.*
        - libdap4 3.18.*  # [not win]
        - libtiff 4.0.*
        - libpng >=1.6.23,<1.7
        - zlib 1.2.*  # [not win]
        - jpeg 9*
        - postgresql  # [not win]
        - giflib 5.1.*  # [not win]
        - json-c  # [not win]
        - freexl
        - openjpeg
        - curl
        - expat
        - sqlite 3.13.*  # [not win]
        - libspatialite  # [not win]
test:
    files:
        - extra_tests.py
        - test_data/sites.dbf
        - test_data/sites.sbn
        - test_data/sites.sbx
        - test_data/sites.shp
        - test_data/sites.shx
        - test_data/cropped.cub
    imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
    commands:
        - ogrinfo sites.shp
        - gdal_grid --version
        - gdal_rasterize --version
        - gdal_translate --version
        - gdaladdo --version
        - gdalenhance --version
        - gdalwarp --version
        - gdalinfo --formats
        #- conda inspect linkages -p $PREFIX gdal  # [not win]

about:
    home: http://www.gdal.org/
    license: MIT
    summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
