{% set version = "2.1.0" %}

package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-{{ version }}.tar.gz
    url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
    md5: 0fc165cd947c54b132204233dfb243f1
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        # fixes compilation problems with jpeg
        # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
        - disable_jpeg12.patch  # [win]
        - install_scripts.patch

build:
    number: 4
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - hdf4
        - hdf5 1.8.15*
        - geos
        - proj.4
        - xerces-c
        - libnetcdf 4.3*
        - kealib
        - krb5
        - libtiff 4.0.6
        - libpng 1.6*
        - zlib 1.2*  # [not win]
        - jpeg 9*
        - postgresql  # [not win]
        - openjpeg
        - curl
        - sqlite
        - libspatialite  # [not win]

    run:
        - python
        - numpy x.x
        - hdf4
        - hdf5 1.8.15*
        - geos
        - proj.4
        - xerces-c
        - libnetcdf 4.3*
        - kealib
        - krb5
        - libtiff 4.0.6
        - libpng 1.6*
        - zlib 1.2*  # [not win]
        - jpeg 9*
        - postgresql  # [not win]
        - openjpeg
        - curl
        - sqlite 
        - libspatialite  # [not win]

test:
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
    imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
    commands:
        - ogrinfo sites.shp
        - gdal_grid --version
        - gdal_rasterize --version
        - gdal_translate --version
        - gdaladdo --version
        - gdalenhance --version
        - gdalwarp --version
        - gdalinfo --formats

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
