{% set version = "2.3.0" %}

package:
  name: gdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 6f75e49aa30de140525ccb58688667efe3a2d770576feb7fbc91023b7f552aa2
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 and py36)]

requirements:
  build:
    - python
    - m2w64-xz  # [win]
    - setuptools
    - cmake  # [win]
    - numpy 1.11.*
    - libgdal {{ version }}
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 and py36)]
  run:
    - python
    - numpy >=1.11
    - libgdal {{ version }}
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 and py36)]

test:
  files:
    - extra_tests.py
    - test_data
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
