package:
    name: gdal
    version: 2.0.2

source:
    fn: gdal-2.0.2.tar.gz
    url: http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz
    md5: 573865f3f59ba7b4f8f4cddf223b52a5
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        - install_scripts.patch

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - hdf4
        - hdf5
        - geos
        - proj.4
        - xerces-c
        - libnetcdf
        - kealib
        - krb5
        - postgresql  # [linux]
        - openjpeg  # [not win]
        - curl  # [not win]
    run:
        - python
        - numpy x.x
        - hdf4
        - hdf5
        - geos
        - proj.4
        - xerces-c
        - libnetcdf
        - kealib
        - krb5
        - postgresql  # [linux]
        - openjpeg  # [not win]
        - curl  # [not win]

test:
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
    imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
    commands:
        - ogrinfo sites.shp  # [not win]
        - ogrinfo.exe sites.shp  # [win]
        - gdal_grid --version  # [not win]
        - gdal_rasterize --version  # [not win]
        - gdal_translate --version  # [not win]
        - gdaladdo --version  # [not win]
        - gdalenhance --version  # [not win]
        - gdalwarp --version  # [not win]
        - gdalinfo --formats  # [not win]

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
