{% set version = "2.3.1" %}

package:
  name: gdal-split
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 9c4625c45a3ee7e49a604ef221778983dd9fd8104922a87f20b99d9bedb7725a
  patches:
  patches:
    # BUILT_AS_DYNAMIC_LIB.
    - patches/windowshdf5.patch
    # Use multiple cores on Windows.
    - patches/multiprocessor.patch
    # disable 12 bit jpeg on Windows as we aren't using internal jpeg
    - patches/disable_jpeg12.patch

build:
  number: 4
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake  # [win]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # Python here is only needed so conda-smithy can get the matrix right.
    # We should probably re-visit this at some point and make it more efficient.
    - python
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml
    - libnetcdf
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - libuuid  # [linux]
    - libxml2
    - openjpeg
    - openssl
    - pcre
    - poppler  # [not win]
    - postgresql
    - proj4
    - sqlite
    - xerces-c
    - xz  # [not win or vc>=14]
    - m2w64-xz  # [win]
    - zlib

outputs:
  - name: libgdal
    script: install_lib.sh   # [unix]
    script: install_lib.bat   # [win]
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libgdal', max_pin='x.x') }}
    requirements:
      build:
        # ranlib used at install time
        - {{ compiler('c') }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
      host:
        - curl
        - expat
        - freexl
        - geos
        - geotiff
        - giflib  # [not win]
        - hdf4
        - hdf5
        - jpeg
        - json-c  # [not win]
        - kealib
        - libdap4  # [not win]
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libxml2
        - openjpeg
        - openssl
        - pcre
        - poppler  # [not win]
        - postgresql
        - proj4
        - sqlite
        - xerces-c
        - xz  # [not win or vc>=14]
        - m2w64-xz  # [win]
        - zlib
      run:
        - curl
        - expat
        - freexl
        - geos
        - geotiff
        - giflib  # [not win]
        - hdf4
        - hdf5
        - jpeg
        - json-c  # [not win]
        - kealib
        - libdap4  # [not win]
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libxml2
        - openjpeg
        - openssl
        - pcre
        - poppler  # [not win]
        - postgresql
        - proj4
        - sqlite
        - xerces-c
        - xz  # [not win or vc>=14]
        - m2w64-xz  # [win]
        - zlib
    test:
      files:
        - test_data
      commands:
        - gdal_grid --version
        - gdal_rasterize --version
        - gdal_translate --version
        - gdaladdo --version
        - gdalenhance --version
        - gdalwarp --version
        - gdalinfo --formats
        - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    about:
      summary: 'The Geospatial Data Abstraction Library (GDAL)'

  - name: gdal
    script: install_python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - cmake  # [win]
        - numpy
        - {{ pin_subpackage('libgdal', exact=True) }}
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('libgdal', exact=True) }}
    test:
      files:
        - test_data
        - extra_tests.py
        - run_tests.py
      imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
      commands:
        - $PYTHON run_tests.py  # [unix]
        - %PYTHON% run_tests.py  # [win]
        - $PYTHON extra_tests.py  # [unix]
        - %PYTHON% extra_tests.py  # [win]
      about:
        summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - gillins
    - kmuehlbauer
    - mingwandroid
    - msarahan
    - ocefpaf
