{% set version = "1.11.4" %}

package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-{{ version }}.tar.gz
    url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
    md5: e9a966f0f5a88c43da47faf78a865952
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        - MSC_VER_1900_snprintf.patch  # [win]
        - install_scripts.patch

build:
    number: 1
    skip: True  # [win and py35]
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - hdf4
        - hdf5
        - geos
        - proj.4
        - xerces-c
        - libnetcdf
        - kealib
        - krb5
        - postgresql  # [linux]
        - openjpeg  # [not win]
        - curl  # [not win]
        - giflib  # [not win]
    run:
        - python
        - numpy x.x
        - hdf4
        - hdf5
        - geos
        - proj.4
        - xerces-c
        - libnetcdf
        - kealib
        - krb5
        - postgresql  # [linux]
        - openjpeg  # [not win]
        - curl  # [not win]
        - giflib  # [not win]

test:
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
    imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
    commands:
        - ogrinfo sites.shp  # [not win]
        - ogrinfo.exe sites.shp  # [win]
        - gdal_grid --version  # [not win]
        - gdal_rasterize --version  # [not win]
        - gdal_translate --version  # [not win]
        - gdaladdo --version  # [not win]
        - gdalenhance --version  # [not win]
        - gdalwarp --version  # [not win]
        - gdalinfo --formats  # [not win]
        - conda inspect linkages gdal --name _test  # [linux]

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
